import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* AppProvider wraps the whole app so every page can read the logged in
          user, the chat list and the users list from one place */}
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
